### ISSUE TITLE
There is a warning with PHP version 7.3

### ISSUE THREAD

**Issue by macway** [ethitter/Taxonomy-Dropdown-Widget#5]
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in 
tag-dropdown-widget.php on line 430

It is described here
https://wordpress.org/support/topic/warning-continue-targeting-switch-is-equivalent-to-break/

Changing "continue" to "continue 2" in the certain line does not throw a warning anymore and seems that is not breaking functionality or performance 
https://stackoverflow.com/questions/26431066/continue-2-and-break-in-switch-statement

**Comment by ethitter** [comment]
Thanks for the reminder. I never got back to merging #4 for some reason. Regardless, a fix is now in `master` care of https://git.ethitter.com/wp-plugins/taxonomy-dropdown-widget/merge_requests/1.
